version: '3'
services:
  postgres:
    container_name: postgres
    image: postgis/postgis
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
volumes:
  db_data:
