version: '3'
services:
  postgres:
    container_name: postgres
    image: postgis/postgis
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./add_extensions.sql:/docker-entrypoint-initdb.d/add_extensions.sql
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
